name = "NumericallyIntegrateArrays"
uuid = "030973e2-ac42-11e9-1c78-e905c061731d"
authors = ["Jishnu Bhattacharya <jishnuonline@gmail.com>"]
version = "0.1.0"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
OffsetArrays = "6fe1bfb0-de20-5000-8ca7-80f57d26f881"

[compat]
OffsetArrays = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]